version: '3.8'

networks:
  internal:
    driver: bridge

services:
  backend:
    image: php:7.4-fpm
    container_name: backend
    volumes:
      - ./mounts/site:/var/www/html
    networks:
      - internal

  frontend:
    image: nginx:1.23-alpine
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./mounts/site:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal

